apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bullsight

resources:
  - namespace.yaml
  - api-config.yaml
  - api-secret.yaml
  - api-pvc.yaml
  - api-deployment.yaml
  - api-service.yaml
  - web-config.yaml
  - web-secret.yaml
  - web-deployment.yaml
  - web-service.yaml
